name: pesonalized_fitness_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2

  cupertino_icons: ^1.0.6

  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/facebookbtn.png
    - assets/images/googelbtn.png
    - assets/images/appLogo.png

    - assets/images/screen1.jpg
    - assets/images/screen2.jpg
    - assets/images/screen3.jpg
    - assets/images/screen4.jpg

    - assets/fonts/Poppins-Thin.ttf
    - assets/fonts/Poppins-Light.ttf
    - assets/fonts/Poppins-MediumItalic.ttf
    - assets/fonts/Poppins-SemiBold.ttf
    - assets/fonts/Montserrat-Regular.ttf
    - assets/fonts/Montserrat-Medium.ttf
    - assets/fonts/Montserrat-SemiBold.ttf
    - assets/fonts/Montserrat-Bold.ttf

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Black.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
